# Generated by Django 4.1 on 2023-09-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Oculi',
        ),
        migrations.RenameField(
            model_name='oculi',
            old_name='amount_available',
            new_name='amount',
        ),
    ]
